name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    # Unit tests temporarily disabled
    # - name: Run unit tests with coverage
    #   run: |
    #     dotnet test tests/AdminService.Tests/AdminService.Tests.csproj \
    #       --no-build \
    #       --verbosity normal \
    #       --collect:"XPlat Code Coverage" \
    #       --results-directory ./coverage-results
    #     
    #     dotnet test tests/Common.Middleware.Tests/Common.Middleware.Tests.csproj \
    #       --no-build \
    #       --verbosity normal \
    #       --collect:"XPlat Code Coverage" \
    #       --results-directory ./coverage-results
    
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Run integration tests with coverage
      run: |
        dotnet test tests/IntegrationTest/IntegrationTest.csproj \
          --no-build \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage-results
    
    - name: Generate coverage report
      run: |
        dotnet reportgenerator \
          -reports:./coverage-results/**/coverage.cobertura.xml \
          -targetdir:./coverage-report \
          -reporttypes:Html
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage-report
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./coverage-results
