name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Run unit tests with coverage
      run: |
        dotnet test tests/AdminService.Tests/AdminService.Tests.csproj \
          --no-build \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage-results
        
        dotnet test tests/Common.Middleware.Tests/Common.Middleware.Tests.csproj \
          --no-build \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage-results
    
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:./coverage-results/**/coverage.cobertura.xml \
          -targetdir:./coverage-report \
          -reporttypes:HtmlInline_AzurePipelines;Cobertura
    
    - name: Run integration tests with Newman
      run: |
        dotnet test tests/IntegrationTest/IntegrationTest.csproj --no-build --verbosity normal
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage-report
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./coverage-results
